version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
  web:
    build: .
    command: "gunicorn hillelDjango4.wsgi 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always
    volumes:
      - .:/app
  migrations:
    build: .
    command: "python manage.py migrate"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: "no"
    volumes:
      - .:/app
